// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Washine;

/************************************************************/
/**
 * 
 */
public class Group {
	/**
	 * 
	 */
	public String group_name;
}
