// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Washine;

/************************************************************/
/**
 * 
 */
public class Invitation {
	/**
	 * 
	 */
	public String invitee_name;
	/**
	 * 
	 */
	public String code;
	/**
	 * 
	 */
	public boolean accepted;
}
