// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Washine;

/************************************************************/
/**
 * 
 */
public class UserGroup {
	/**
	 * 
	 */
	public String name;
}
