// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Washine;

/************************************************************/
/**
 * 
 */
public class User {
	/**
	 * 
	 */
	public String email;
	/**
	 * 
	 */
	public String Id;
	/**
	 * 
	 */
	public String password;
	/**
	 * 
	 */
	public int level;
	/**
	 * 
	 */
	public boolean blocked;
	/**
	 * 
	 */
	public Group[] group;
	/**
	 * 
	 */
	public Invitation invitation;
	/**
	 * 
	 */
	public UserGroup[] usergroup;
}
