// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Washine;

/************************************************************/
/**
 * 
 */
public class Washing {
	/**
	 * 
	 */
	public String id;
	/**
	 * 
	 */
	public String[] enabled_participants;
	/**
	 * 
	 */
	public EDouble current_load;
	/**
	 * 
	 */
	public boolean active;
	/**
	 * 
	 */
	public WashingOptions washingoptions;
}
