// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ClassDiagram.Washine;

/************************************************************/
/**
 * 
 */
public class WashingOptions {
	/**
	 * 
	 */
	public EDate date_time;
	/**
	 * 
	 */
	public int visibility_time;
	/**
	 * 
	 */
	public int duration_minutes;
	/**
	 * 
	 */
	public EDouble initial_load;
	/**
	 * 
	 */
	public EDouble max_load;
	/**
	 * 
	 */
	public String temperature;
	/**
	 * 
	 */
	public String spin_speed;
	/**
	 * 
	 */
	public String fabric_type;
	/**
	 * 
	 */
	public String color;
	/**
	 * 
	 */
	public String detergent_type;
	/**
	 * 
	 */
	public String refund_type;
	/**
	 * 
	 */
	public String pickup_address;
	/**
	 * 
	 */
	public String delivery_address;
	/**
	 * 
	 */
	public String drying;
	/**
	 * 
	 */
	public String pickup_availability;
	/**
	 * 
	 */
	public String delivery_availability;
	/**
	 * 
	 */
	public boolean ironing;
	/**
	 * 
	 */
	public EDouble participant_max_load;
	/**
	 * 
	 */
	public EDate washing_access_open_date;
	/**
	 * 
	 */
	public EDate washing_access_close_date;
	/**
	 * 
	 */
	public boolean Underwear;
}
