CREATE TABLE IF NOT EXISTS UTENTE (
Id TEXT PRIMARY KEY,
Email TEXT NOT NULL,
Password TEXT NOT NULL,
Livello INTEGER NOT NULL,
Bloccato BOOLEAN DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS GRUPPO ( 
IdUtente TEXT PRIMARY KEY,
NomeGruppo TEXT NOT NULL,
FOREIGN KEY (IdUtente) REFERENCES UTENTE(Id)
);
CREATE TABLE IF NOT EXISTS LISTAUTENTIGRUPPO (
IdLavandaio TEXT PRIMARY KEY,
IdPartecipante TEXT NOT NULL,
Nome TEXT NOT NULL,
FOREIGN KEY (IdLavandaio) REFERENCES UTENTE(Id),
FOREIGN KEY (IdPartecipante) REFERENCES UTENTE(Id)
);
CREATE TABLE IF NOT EXISTS INVITI (
IdLavandaio TEXT PRIMARY KEY,
NomeInvitato TEXT NOT NULL,
Codice TEXT NOT NULL,
Accettato BOOLEAN DEFAULT FALSE, 
FOREIGN KEY (IdLavandaio) REFERENCES UTENTE(Id)
);
CREATE TABLE IF NOT EXISTS LAVAGGIO (
IdLavaggio TEXT PRIMARY KEY,
IdLavandaio TEXT NOT NULL,
FOREIGN KEY (IdLavandaio) REFERENCES UTENTE(Id)
);
CREATE TABLE IF NOT EXISTS PARTECIPAZIONELAVAGGIO ( 
IdLavaggio TEXT PRIMARY KEY,
IdPartecipante TEXT NOT NULL,
FOREIGN KEY (IdLavaggio) REFERENCES LAVAGGIO(IdLavaggio),
FOREIGN KEY (IdPartecipante) REFERENCES UTENTE(Id)
);
CREATE TABLE IF NOT EXISTS OPZIONELAVAGGIO (
IdLavaggio TEXT PRIMARY KEY,
TempoVisibilita INTEGER NOT NULL,
DataOra DATE NOT NULL,
DurataMinuti INTEGER NOT NULL,
CaricoIniziale DOUBLE NOT NULL,
CaricoMax DOUBLE NOT NULL,
Temperatura TEXT NOT NULL,
NumeroGiri TEXT NOT NULL,
TipoTessuti TEXT NOT NULL,
Colore TEXT NOT NULL,
TipoDetersivi TEXT NOT NULL,
TipoRimborso TEXT NOT NULL,
Intimo BOOLEAN NOT NULL,
IndirizzoRitiro TEXT,
IndirizzoConsegna TEXT,
DisponibilitaRitiro TEXT,
DisponibilitaConsegna TEXT,
Asciugatura TEXT,
Stiratura BOOLEAN,
CaricoMaxPartecipante DOUBLE,
DataAperturaAccessoLavaggio DATE,
DataChiusuraAccessoLavaggio DATE,
FOREIGN KEY (IdLavaggio) REFERENCES LAVAGGIO (IdLavaggio)
);